CREATE TABLE IF NOT EXISTS duplicate_review (
  dup_key VARCHAR(768) PRIMARY KEY,
  status ENUM('NEW','IGNORE','CONFIRMED','MERGED') NOT NULL DEFAULT 'NEW',
  note TEXT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
