export function apiUrl(path: string): string;
export function assetUrl(path: string): string;
export function fetchBooks(params?: Record<string, unknown>): Promise<any>;
export function fetchBook(id: number | string): Promise<any>;
export function addBook(payload?: Record<string, unknown>, coverFile?: File | null): Promise<any>;
export function updateBook(payload?: Record<string, unknown>): Promise<any>;
export function deleteBook(id: number | string): Promise<any>;
export function restoreBook(id: number | string): Promise<any>;
export function suggestPublishers(q: string): Promise<any>;
export function suggestAuthors(q: string): Promise<any>;
export function createAuthor(payload?: Record<string, unknown>): Promise<any>;
export function fetchAuthors(args?: Record<string, unknown>): Promise<any>;
export function deleteAuthor(authorId: number | string): Promise<any>;
export function updateAuthor(authorId: number | string, payload?: Record<string, unknown>): Promise<any>;
export function login(username: string, password: string): Promise<any>;
export function logout(): Promise<any>;
export function me(): Promise<any>;
export function updateUserPreferences(payload?: Record<string, unknown>, logoFile?: File | null): Promise<any>;
export function fetchUserPreferences(): Promise<any>;
export function fetchOrphanMaintenance(): Promise<any>;
export function deleteOrphanAuthor(authorId: number): Promise<any>;
export function deleteOrphanPublisher(publisherId: number): Promise<any>;
export function deleteOrphanLink(bookId: number, authorId: number): Promise<any>;
export function reassignOrphanLink(bookId: number, authorId: number, newAuthorId: number): Promise<any>;
export function updateOrphanAuthor(authorId: number, payload?: Record<string, unknown>): Promise<any>;
export function updateOrphanPublisher(publisherId: number, payload?: Record<string, unknown>): Promise<any>;
export function listUsers(): Promise<any>;
export function listAuthEvents(params?: Record<string, unknown>): Promise<any>;
export function purgeAuthEvents(months: number): Promise<any>;
export function purgeCatalog(confirm?: string): Promise<any>;
export function createUser(payload?: Record<string, unknown>): Promise<any>;
export function updateUser(payload?: Record<string, unknown>): Promise<any>;
export function deleteUser(userId: number | string): Promise<any>;
export function changePassword(payload?: Record<string, unknown>): Promise<any>;
export function adminResetPassword(payload?: Record<string, unknown>): Promise<any>;
